language: php

php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=hosted-jft-plugin-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=hosted-jft
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=hosted-jft-plugin.zip
    - PLUGIN="hosted-jft"
    - MAINFILE="hosted-jft-plugin.php"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*vendor*" -x "Dockerfile" -x "*assets*" -x "composer.*" -x "docker-compose.yml" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    - curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
    - chmod +x deploy-wordpress.sh
    - curl -LO https://raw.githubusercontent.com/bmlt-enabled/release-notes-tool/master/release-notes.sh
    - chmod +x release-notes.sh
    - ./release-notes.sh readme.txt "wp"
    deploy:
    - provider: s3
      access_key_id: AKIAI7JHYFA6DI3WYP5A
      secret_access_key:
        secure: ojTGcwwpR5sAdXnQzLVMlUixniK60pzjege20rHhnqDvIzWdqo+fEVEnpiRt2GqgAXTF+sKd6dQP+KGVf6IY9eIK0G7iQE9ILrafcmv02rneJsZEoZDczHEtVYRIkLjzB2SY81RH79UPHIiXDYdqS+YXT/b1qbKSsd1m/hQz+c1UzZJicFsL8avPwQiwuhRHO6hv4PVlAp87rRUKdYrLE9KqrxFfzP48blZkQL6ydn63hjEQaQlHF3wJFsTFTGmsou5yk4bprzN1yI7WBk/aKClf/SUbpB3hYaLFP6CGF3Xjtrhiu1FF+izsavWkONS9wSL7CfQN9yk2pr2YxOz84udCkBQAbAOg0rXH+Zpm8n/CxVHU0wzBWGIoeWH4wfv/iX1HzGW+fYQPfuX6bew/GwqsfCJ2uCa1lm1cYVA1KaYUk56wZWX9tTQzbLk2pY32kWnanmGhVmhzNp6tZ/E9+rhzmAikzsDpLbU4C5/Ku+bdDbt6wP/J8w8mVK0lOcJ3bMatHCduUvQaQ4f/wZBVoeFiqUPF/w8UgUP3DOGkuP9w0k66RLKELXw7EV/XVUGsNomxQkc0qINWbLSInC15L1g7UIurux5Uv0/d/pnsU+BbyJK1UD2tI91pokqAL/IUIZj0SsO6A1uc30zt7+sZ1npIcoxALzgvEeOHlYzefys=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      edge: true
      release_notes_file: "changelog.txt"
      token:
        secure: RBJ7vAQy3uPsrhxDY5wydLDOqgkzcVaiIOuOtQ63YPkqygFWlurhus1ZToWOTVczggJ7nxl1QCMPXCm+XYxrkhK2eUrZtf062TF6V/K8A43wnPc4V5hsiIdvjER2FWb7jecDFfxikh8V7MmyMXOG9QbHd2nX9ar+XLKFmLcPPsL/AEiI8kYdK/XeO7/oB+npDYKHU09S0IEPoEijx8QT4OCoqx3OQJl/qA+E0E/eoxMtgU7knPXYHaTszaOSdW92wT/cy7HMDe+ZW801zkgMrvxOvfEcmjDMwlvbRsRZfmVVKyk7x2M4uo7Lb/rGV4gC6WAwGY73W5dPxvHxJatkWpxyLDX+8GkI0vIoFDsgtzwpsBVLvHxEPB5uiZOYFGp1MlKL/onLSrqjza99ZVpwu/zvYxjyyGpPPwHaDcq3hOdwDxeHzy2e7Jr5428asrA0nLZaTiS43pRsh5ttAkvdnpu2/rN6Di74Tu58Pzf/6zgM1kfckZBY/CVUsNTpB82pEpH1hPm0DbEbNfKHeryYQGqtw5Chz6aL8oMyI56W3E8jml3UXI1iuMhENO3F/FnbdAyWBHKfVY6vnLiM12zYmsDOchtdBORj7CYrUATwbrSS5wibhf9lQ88MCoGamcYUmXVUVh6VKGS3JzdPgu6kWHoqHXRJqxY9agg/8f0JPrk=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      name: "$TRAVIS_TAG"
      on:
        tags: true
        condition: $TRAVIS_TAG != *beta*
    - provider: releases
      api_key:
        secure: RBJ7vAQy3uPsrhxDY5wydLDOqgkzcVaiIOuOtQ63YPkqygFWlurhus1ZToWOTVczggJ7nxl1QCMPXCm+XYxrkhK2eUrZtf062TF6V/K8A43wnPc4V5hsiIdvjER2FWb7jecDFfxikh8V7MmyMXOG9QbHd2nX9ar+XLKFmLcPPsL/AEiI8kYdK/XeO7/oB+npDYKHU09S0IEPoEijx8QT4OCoqx3OQJl/qA+E0E/eoxMtgU7knPXYHaTszaOSdW92wT/cy7HMDe+ZW801zkgMrvxOvfEcmjDMwlvbRsRZfmVVKyk7x2M4uo7Lb/rGV4gC6WAwGY73W5dPxvHxJatkWpxyLDX+8GkI0vIoFDsgtzwpsBVLvHxEPB5uiZOYFGp1MlKL/onLSrqjza99ZVpwu/zvYxjyyGpPPwHaDcq3hOdwDxeHzy2e7Jr5428asrA0nLZaTiS43pRsh5ttAkvdnpu2/rN6Di74Tu58Pzf/6zgM1kfckZBY/CVUsNTpB82pEpH1hPm0DbEbNfKHeryYQGqtw5Chz6aL8oMyI56W3E8jml3UXI1iuMhENO3F/FnbdAyWBHKfVY6vnLiM12zYmsDOchtdBORj7CYrUATwbrSS5wibhf9lQ88MCoGamcYUmXVUVh6VKGS3JzdPgu6kWHoqHXRJqxY9agg/8f0JPrk=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      prerelease: true
      on:
        tags: true
        condition: $TRAVIS_TAG =~ "beta"
#    - provider: script
#      script: ./deploy-wordpress.sh
#      skip_cleanup: true
#      on:
#        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
